image: python:3.6
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

stages:
  - initial
  # - lint
  # - test
  # - docs
  # - build_base
  # - build
  # - publish
  # - review
  # - production

cache:
  paths:
    - .cache/pip
    - venv/

install_e2e:
  stage: initial
  script:
    - python -m venv venv
    - source ./venv/bin/activate
    - meltano --version
    - pip install -e .
    - ls
    - pwd
    - mkdir -p /home/projects
    - cd /home/projects
    - meltano init test_project