image: python:3.6
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

stages:
  - test
  # - production

lighthouse:
  image: "femtopixel/google-lighthouse"
  stage: test
  artifacts:
    paths:
      - "/builds/meltano/meltano/lighthouse-results.html"
  script:
    - python --version
    - lighthouse --output-path="./lighthouse-results.html" --chrome-flags="--headless --disable-gpu" http://jacobschatz.com
