image: python:3.6
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

stages:
  - initial
  # - lint
  # - test
  # - docs
  # - build_base
  # - build
  # - publish
  # - review
  # - production

cache:
  paths:
    - .cache/pip
    - venv/

install_e2e:
  stage: initial
  script:
    - python -m venv venv
    - python --version
    - source ./venv/bin/activate
    - pip install -e .
    - apt-get update
    - curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - node -v
    - npm -v
    - npm install yarn
    - make bundle
    - meltano --versiong
    - ls
    - pwd
    - mkdir -p /home/projects
    - cd /home/projects
    - meltano init test_project