name: meltano
root: <%= ENV["MELTANO_PROJECT"] || '.' %>
pre_window: source <%= ENV["MELTANO_VENV"] || ".venv" %>/bin/activate
startup_window: shell

windows:
  - repo:
      layout: even-vertical
      panes:
        - cd <%= ENV["MELTANO_ROOT"] %>; clear
  - db:
      layout: even-vertical
      panes: 
        - docker-compose up warehouse_db     # start the warehouse
  - meltano:
      layout: even-vertical
      panes:
        - FLASK_ENV=development meltano ui              # start the api
        - cd <%= ENV["MELTANO_ROOT"] %>/src/webapp; yarn && yarn serve  # start the ui
  - project:
      layout: even-vertical
      panes:
        - clear
        - tail -f .meltano/run/meltano-ui.log
