.only:version-tags:
  only:
    refs:
      - tags@meltano/meltano
    variables:
      - $CI_COMMIT_TAG =~ /^v*/

.only:master:
  only:
    - master@meltano/meltano

.only:testables:
  only:
    refs:
      - master
      - /^release-/
      - tags
      - merge_requests
