publish_trigger:
  # Dummy job. Administrator triggers this job manually to allow other publish jobs to run.
  when: manual
  extends:
    - .only:release-branches
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    entrypoint: [""]
  stage: publish
  script:
    - MELTANO_VERSION="${CI_COMMIT_REF_NAME#release/v}"
    - echo "Triggering publish step for v$MELTANO_VERSION (git ref '$CI_COMMIT_REF_NAME')"

pypi_publish:
  extends:
    - .only:release-branches
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    entrypoint: [""]
  stage: publish
  needs: [publish_trigger]
  before_script:
    - pip install poetry
  script:
    # grab the built package
    - ln -s /meltano/dist
    - poetry publish

# Manages:
#  - meltano/meltano:<sha>-python<version>
#  - meltano/meltano:<tag>-python<version>
#  - meltano/meltano:latest-python<version>
#  - meltano/meltano:<tag>
#  - meltano/meltano:latest
gitlab_images_publish:
  extends:
    - .build_prod
    - .only:release-branches
  script:
    - source .gitlab/ci/scripts/docker_build_script.sh

    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$CI_COMMIT_TAG-python$PYTHON_IMAGE_VERSION
    - docker push $IMAGE_NAME:$CI_COMMIT_TAG-python$PYTHON_IMAGE_VERSION

    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest-python$PYTHON_IMAGE_VERSION
    - docker push $IMAGE_NAME:latest-python$PYTHON_IMAGE_VERSION

    - '[[ "$PYTHON_VERSION" == "3.6" ]] && docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$CI_COMMIT_TAG || true'
    - '[[ "$PYTHON_VERSION" == "3.6" ]] && docker push $IMAGE_NAME:$CI_COMMIT_TAG || true'

    - '[[ "$PYTHON_VERSION" == "3.6" ]] && docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest || true'
    - '[[ "$PYTHON_VERSION" == "3.6" ]] && docker push $IMAGE_NAME:latest || true'

# registry.gitlab.com/meltano/meltano:<tag>-python<version> → docker.io/meltano:<tag>-python<version>
# registry.gitlab.com/meltano/meltano:latest-python<version> → docker.io/meltano:latest-python<version>
# registry.gitlab.com/meltano/meltano:<tag> → docker.io/meltano:<tag>
# registry.gitlab.com/meltano/meltano:latest → docker.io/meltano:latest
dockerhub_publish:
  extends:
    - .parallel:image_tag_suffix
    - .only:release-branches
  image: docker:latest
  stage: publish
  needs: [publish_trigger]
  services:
    - docker:dind
  variables:
    DOCKERFILE: .
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: meltano/meltano
    SOURCE_IMAGE: $CI_REGISTRY_IMAGE
  script:
    - MELTANO_VERSION="${CI_COMMIT_REF_NAME#release/v}"
    - echo "Publishing docker images for v$MELTANO_VERSION (git ref '$CI_COMMIT_REF_NAME')"

    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

    - docker pull $SOURCE_IMAGE:$MELTANO_VERSION$IMAGE_TAG_SUFFIX
    - docker tag $SOURCE_IMAGE:$MELTANO_VERSION$IMAGE_TAG_SUFFIX $IMAGE_NAME:$MELTANO_VERSION$IMAGE_TAG_SUFFIX
    - docker push $IMAGE_NAME:$MELTANO_VERSION$IMAGE_TAG_SUFFIX

    - docker pull $SOURCE_IMAGE:latest$IMAGE_TAG_SUFFIX
    - docker tag $SOURCE_IMAGE:latest$IMAGE_TAG_SUFFIX $IMAGE_NAME:latest$IMAGE_TAG_SUFFIX
    - docker push $IMAGE_NAME:latest$IMAGE_TAG_SUFFIX
