# This file defines the release process, including version bump, manual trigger, and auto-publish steps.

triggered_version_bump:
  # This job triggers for any branches named like `release/vX.Y.Z`
  # The job will automatically flush the changelog, bump version refs,
  # and commit and push the result back to the branch.
  extends:
    - .only:release-branches
  except:
    - tags
  stage: docs
  before_script:
    # - git config --global user.name "${GITLAB_USER_NAME}"
    # - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.email "hello@meltano.com"
    - git config --global user.name "Gitlab CI (bot)"
    - pip install changelog-cli bumpversion
    # - poetry install 
  script:
    - |
      echo "Setting up 'discovery.yml' sync from 'hub.meltano.com'..."
      echo "Current location: Ref='$CI_COMMIT_REF_NAME' and Namespace='$CI_PROJECT_NAMESPACE'..."
    - |
      echo "Detecting and validating version number..."
      CURR_VER="$(bumpversion major --allow-dirty --dry-run --list | grep current_version= | cut -d'=' -f2)"
      NEW_VER="${CI_COMMIT_REF_NAME#release/v}"
      echo "Detected current version '$CURR_VER' and new version '$NEW_VER'"
      [[ "$CURR_VER" == "" ]] && echo "Could not detect current version" && exit 1
      [[ "$NEW_VER" == "" ]] && echo "Could not detect new version" && exit 1
      [[ "$NEW_VER" == "$CURR_VER" ]] && echo "Version is already bumped. Aborting job." && exit 0
      MAJOR_BUMP="$(bumpversion major --allow-dirty --dry-run --list | grep new_version= | cut -d'=' -f2)"
      MINOR_BUMP="$(bumpversion minor --allow-dirty --dry-run --list | grep new_version= | cut -d'=' -f2)"
      PATCH_BUMP="$(bumpversion patch --allow-dirty --dry-run --list | grep new_version= | cut -d'=' -f2)"
      [[ $NEW_VER = $MAJOR_BUMP ]] && BUMP_TYPE="major"
      [[ $NEW_VER = $MINOR_BUMP ]] && BUMP_TYPE="minor"
      [[ $NEW_VER = $PATCH_BUMP ]] && BUMP_TYPE="patch"
      [[ "$BUMP_TYPE" == "" ]] && echo "Could not detect version bump type from version text '$NEW_VER'" && exit 1
      echo "Detected bump type '$BUMP_TYPE' from '$CURR_VER' to '$NEW_VER'"
      echo "Flushing changelog entries with '--$BUMP_TYPE' flag..."
      changelog release --$BUMP_TYPE --yes
      echo "Adding changelog to git..."
      git add CHANGELOG.md
      echo "Bumping version entries..."
      bumpversion $BUMP_TYPE --tag --allow-dirty --new-version=$NEW_VER
      echo "Pushing branch updates..."
      git push http://root:$CI_COMMITS_GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:$CI_COMMIT_REF_NAME

publish_trigger:
  # Dummy job. Administrator triggers this job manually to allow other publish jobs to run.
  when: manual
  extends:
    - .only:release-branches
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    entrypoint: [""]
  stage: publish
  script:
    - MELTANO_VERSION="${CI_COMMIT_REF_NAME#release/v}"
    - echo "Triggering publish step for v$MELTANO_VERSION (git ref '$CI_COMMIT_REF_NAME')"

pypi_publish:
  extends:
    - .only:release-branches
  image:
    name: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    entrypoint: [""]
  stage: publish
  needs: [publish_trigger]
  before_script:
    - pip install poetry
  script:
    # grab the built package
    - ln -s /meltano/dist
    - poetry publish

# Manages:
#  - meltano/meltano:<sha>-python<version>
#  - meltano/meltano:<tag>-python<version>
#  - meltano/meltano:latest-python<version>
#  - meltano/meltano:<tag>
#  - meltano/meltano:latest
gitlab_images_publish:
  extends:
    - .build_prod
    - .only:release-branches
  script:
    - source .gitlab/ci/scripts/docker_build_script.sh

    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$CI_COMMIT_TAG-python$PYTHON_IMAGE_VERSION
    - docker push $IMAGE_NAME:$CI_COMMIT_TAG-python$PYTHON_IMAGE_VERSION

    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest-python$PYTHON_IMAGE_VERSION
    - docker push $IMAGE_NAME:latest-python$PYTHON_IMAGE_VERSION

    - '[[ "$PYTHON_VERSION" == "3.6" ]] && docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$CI_COMMIT_TAG || true'
    - '[[ "$PYTHON_VERSION" == "3.6" ]] && docker push $IMAGE_NAME:$CI_COMMIT_TAG || true'

    - '[[ "$PYTHON_VERSION" == "3.6" ]] && docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest || true'
    - '[[ "$PYTHON_VERSION" == "3.6" ]] && docker push $IMAGE_NAME:latest || true'

# registry.gitlab.com/meltano/meltano:<tag>-python<version> → docker.io/meltano:<tag>-python<version>
# registry.gitlab.com/meltano/meltano:latest-python<version> → docker.io/meltano:latest-python<version>
# registry.gitlab.com/meltano/meltano:<tag> → docker.io/meltano:<tag>
# registry.gitlab.com/meltano/meltano:latest → docker.io/meltano:latest
dockerhub_publish:
  extends:
    - .parallel:image_tag_suffix
    - .only:release-branches
  image: docker:latest
  stage: publish
  needs: [publish_trigger]
  services:
    - docker:dind
  variables:
    DOCKERFILE: .
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: meltano/meltano
    SOURCE_IMAGE: $CI_REGISTRY_IMAGE
  script:
    - MELTANO_VERSION="${CI_COMMIT_REF_NAME#release/v}"
    - echo "Publishing docker images for v$MELTANO_VERSION (git ref '$CI_COMMIT_REF_NAME')"

    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

    - docker pull $SOURCE_IMAGE:$MELTANO_VERSION$IMAGE_TAG_SUFFIX
    - docker tag $SOURCE_IMAGE:$MELTANO_VERSION$IMAGE_TAG_SUFFIX $IMAGE_NAME:$MELTANO_VERSION$IMAGE_TAG_SUFFIX
    - docker push $IMAGE_NAME:$MELTANO_VERSION$IMAGE_TAG_SUFFIX

    - docker pull $SOURCE_IMAGE:latest$IMAGE_TAG_SUFFIX
    - docker tag $SOURCE_IMAGE:latest$IMAGE_TAG_SUFFIX $IMAGE_NAME:latest$IMAGE_TAG_SUFFIX
    - docker push $IMAGE_NAME:latest$IMAGE_TAG_SUFFIX
